name: Android CI

on:
  pull_request:

permissions: write-all

jobs:

  build_assemble:
    runs-on: ubuntu-latest
    env:
      OUTPUT_DIR: build/libs
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      # https://github.com/burrunan/gradle-cache-action
      - uses: burrunan/gradle-cache-action@v1
        name: Cache gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build jar
        run: ./gradlew jar

      - name: Upload Cli
        uses: actions/upload-artifact@v3
        with:
          name: apk-size-diff-cli.jar
          path: build/libs/*.jar
          # 缓存1天
          retention-days: 1